In [1]:
import pandas as pd
import sklearn
import numpy as np

In [2]:
df=pd.read_excel("money3.xlsx")

In [3]:
df=df.curs

In [4]:
df=pd.DataFrame(df)

In [5]:
mon=df.values

In [6]:
X_train=[]
y_train=[]
for i in range(len(mon)-3):
    if i % 7 !=0:
        X_train.append(mon[i])
    else:
        y_train.append(mon[i])   

In [7]:
len(X_train)

672

In [8]:
X_train = [X_train[x:x+6] for x in range(0, len(X_train), 6)]
X_train_real=X_train

In [9]:
len(X_train_real)

112

In [10]:
train_data=X_train_real[:-30]
train_label=y_train[:-30]

In [11]:
test_data=X_train_real[-30:]
test_label=y_train[-30:]

In [31]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [16]:
nice=pd.DataFrame(train_data)

In [64]:
reg=RandomForestRegressor(n_estimators=1500, random_state=0, criterion='mae', max_features=4)
reg.fit(nice, train_label)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestRegressor(bootstrap=True, criterion='mae', max_depth=None,
                      max_features=4, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1500,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [65]:
proba=reg.predict(pd.DataFrame(test_data))
print(mean_absolute_error(test_label, proba))
print(reg.feature_importances_)

2.286908430000301
[0.35341506 0.26133034 0.10122402 0.05603337 0.05981114 0.16818607]


In [66]:
proba

array([63.9889088 , 64.931729  , 64.4705656 , 63.9313624 , 63.40908267,
       64.32526087, 63.8207844 , 64.25827847, 62.7634934 , 62.60707613,
       61.866222  , 62.28991873, 62.53295913, 63.70390427, 63.78488007,
       66.6870111 , 68.28651887, 68.28651887, 68.28651887, 68.28651887,
       68.28651887, 68.28651887, 68.28651887, 68.10677227, 68.28300387,
       68.25850233, 68.28651887, 68.28651887, 68.28651887, 68.28651887])

In [38]:
test_label

[array([63.9453]),
 array([65.4399]),
 array([64.2237]),
 array([63.6336]),
 array([63.7748]),
 array([63.853]),
 array([63.843]),
 array([64.4097]),
 array([63.5653]),
 array([62.4071]),
 array([61.9057]),
 array([61.5333]),
 array([62.8299]),
 array([62.7977]),
 array([63.3085]),
 array([65.6097]),
 array([72.0208]),
 array([80.157]),
 array([76.4074]),
 array([73.7145]),
 array([74.7163]),
 array([73.8725]),
 array([72.3381]),
 array([70.752]),
 array([68.6745]),
 array([69.5725]),
 array([70.4413]),
 array([70.88]),
 array([71.9628]),
 array([72.2348])]